# Generated by Django 4.2.14 on 2024-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainoperator",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="trainoperator",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
