# Generated by Django 4.2.14 on 2024-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_management", "0002_alter_trainoperator_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
