# Deployment configuration file for Kubernetes and is used to create and manage the application pods. This file is used to describe a desired state for the application that Kubernetes will maintain.
apiVersion: apps/v1  # Specifies the API version
kind: Deployment  # Indicates that this is a deployment object
metadata:
  name: flight-ticket-management-deployment  # Name of the deployment
  labels:
    app: flight-ticket-management  # Label to identify the app
spec:
  replicas: 2  # Number of pod replicas to run
  selector:
    matchLabels:
      app: flight-ticket-management  # Selector to identify the pods managed by this deployment
  template:
    metadata:
      labels:
        app: flight-ticket-management  # Label for the pods
    spec:
      containers:
        - name: flight-ticket-management  # Name of the container
          image: isrkan/flight-ticket-management:latest  # Docker image for the container from Docker Hub
          ports:
            - containerPort: 8080  # Port the container listens on
          env:  # Environment variables for the container
            - name: SPRING_PROFILES_ACTIVE
              value: "development"  # Sets the active Spring profile to 'development'
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/template1?createDatabaseIfNotExist=true"  # Database connection URL
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres1"
